
    %recordformat                             Eventfm                               (%integer Event, Sub, Extra, Ra, Fp, Sb,%string(255) Message)
    %external   %routine                %spec init          %alias "_XLL_INIT"
    %external   %integer        %fn     %spec GetEvent      %alias "_XGETEVENT"
    %external   %integer        %fn     %spec GetSub        %alias "_XGETSUB"
    %external   %integer        %fn     %spec GetExtra      %alias "_XGETEXTRA"
    %external   %integer        %fn     %spec GetMsgLen     %alias "_XGETMSGLEN"
    %external   %string(255)    %fn     %spec GetMessage    %alias "_XGETMESSAGE"
    %external   %routine                %spec SetEvent      %alias "_XSETEVENT"     ( %integer e )
    %external   %routine                %spec SetSub        %alias "_XSETSUB"       ( %integer s )
    %external   %routine                %spec SetExtra      %alias "_XSETEXTRA"	    ( %integer e )
    %external   %routine                %spec SetMessage    %alias "_XSETMESSAGE"   ( %string(*) %name m )

%endoffile
